# Generated by Django 3.0.3 on 2020-04-27 23:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='الاسم:')),
                ('subtitle', models.CharField(max_length=50, verbose_name='نبذه عنك:')),
                ('address', models.CharField(max_length=50, verbose_name='المحافظه :')),
                ('address_detail', models.CharField(blank=True, max_length=50, null=True, verbose_name='العنوان بالتفصيل :')),
                ('number_phone', models.CharField(max_length=50, verbose_name='الهاتف :')),
                ('work_hour', models.CharField(max_length=50, verbose_name='عدد ساعات العمل :')),
                ('witing_time', models.IntegerField(blank=True, null=True, verbose_name='مده الانتظار :')),
                ('doctor', models.CharField(blank=True, max_length=50, null=True, verbose_name='دكتور ؟ :')),
                ('specialist_doctor', models.CharField(blank=True, max_length=50, null=True, verbose_name='تخصص في :')),
                ('who_i', models.TextField(max_length=250, verbose_name='من انا :')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='سعر الكشف :')),
                ('image', models.ImageField(blank=True, null=True, upload_to='profile', verbose_name='الصوره الشخصيه:')),
                ('slug', models.SlugField(blank=True, null=True, verbose_name='slug :')),
                ('faceBook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('Google', models.CharField(blank=True, max_length=100, null=True)),
                ('type_of_person', models.CharField(choices=[('M', 'male'), ('F', 'Female')], max_length=100, verbose_name='النوع :')),
                ('join_new', models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الانضمام :')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
