# Generated by Django 3.0.3 on 2020-04-27 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='join_new',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='type_of_person',
        ),
    ]
