# Generated by Django 3.0.3 on 2020-04-27 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0002_auto_20200427_2304'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='join_new',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='وقت الانضمام :'),
        ),
        migrations.AddField(
            model_name='profile',
            name='type_of_person',
            field=models.CharField(choices=[('M', 'male'), ('F', 'Female')], default=1, max_length=100, verbose_name='النوع :'),
            preserve_default=False,
        ),
    ]
