# Generated by Django 3.0.3 on 2020-04-28 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acounts', '0003_auto_20200427_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='surname',
            field=models.CharField(default=1, max_length=50, verbose_name='اللقب :'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='profile',
            name='doctor',
            field=models.CharField(blank=True, choices=[('انف و اذن وحنجره', 'انف و اذن وحنجره'), ('جراحه اطفال', 'جراحه اطفال'), ('اطفال حديثي الولاده', 'اطفال حديثي الولاده'), ('اوعيه دمويه', 'اوعيه دمويه'), ('نساء و توليد', 'نساء و توليد'), ('سمنه', 'سمنه'), ('مخ و اعصاب', 'مخ و اعصاب'), ('باطنه', 'باطنه'), ('تجميل', 'تجميل'), ('نفسي', 'نفسي'), ('آورام', 'آورام'), ('قلب', 'قلب'), ('عظام', 'عظام'), ('اسنان', 'اسنان'), ('جلديه', 'جلديه')], max_length=50, null=True, verbose_name='دكتور ؟ :'),
        ),
    ]
